import { Product } from '../types';

export const products: Product[] = [
  {
    id: '1',
    name: 'بانادول إكسترا',
    nameEn: 'Panadol Extra',
    price: 12.50,
    originalPrice: 15.00,
    image: 'https://images.pexels.com/photos/3683074/pexels-photo-3683074.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Medicines',
    description: 'مسكن للألم وخافض للحرارة، يحتوي على الباراسيتامول والكافيين',
    inStock: true,
    rating: 4.5,
    reviews: 128,
    discount: 17,
    isNew: false,
    isBestseller: true
  },
  {
    id: '2',
    name: 'فيتامين د3',
    nameEn: 'Vitamin D3',
    price: 45.00,
    image: 'https://images.pexels.com/photos/3683107/pexels-photo-3683107.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vitamins & Supplements',
    description: 'مكمل غذائي لتقوية العظام والمناعة، 1000 وحدة دولية',
    inStock: true,
    rating: 4.8,
    reviews: 89,
    isNew: true
  },
  {
    id: '3',
    name: 'كريم مرطب للبشرة',
    nameEn: 'Moisturizing Cream',
    price: 28.75,
    originalPrice: 35.00,
    image: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Skincare',
    description: 'كريم مرطب طبيعي للبشرة الجافة والحساسة، خالي من البارابين',
    inStock: true,
    rating: 4.3,
    reviews: 67,
    discount: 18
  },
  {
    id: '4',
    name: 'شامبو الأطفال',
    nameEn: 'Baby Shampoo',
    price: 22.00,
    image: 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Baby Products',
    description: 'شامبو لطيف للأطفال، خالي من الدموع ومناسب للاستخدام اليومي',
    inStock: true,
    rating: 4.7,
    reviews: 156,
    isBestseller: true
  },
  {
    id: '5',
    name: 'جهاز قياس الضغط',
    nameEn: 'Blood Pressure Monitor',
    price: 185.00,
    image: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Medical Devices',
    description: 'جهاز رقمي لقياس ضغط الدم، دقيق وسهل الاستخدام',
    inStock: false,
    rating: 4.6,
    reviews: 43
  },
  {
    id: '6',
    name: 'غسول الفم',
    nameEn: 'Mouthwash',
    price: 18.50,
    image: 'https://images.pexels.com/photos/3685530/pexels-photo-3685530.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Personal Care',
    description: 'غسول الفم المضاد للبكتيريا، ينعش النفس ويحمي اللثة',
    inStock: true,
    rating: 4.2,
    reviews: 92
  },
  {
    id: '7',
    name: 'أوميجا 3',
    nameEn: 'Omega 3',
    price: 65.00,
    originalPrice: 75.00,
    image: 'https://images.pexels.com/photos/3683107/pexels-photo-3683107.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vitamins & Supplements',
    description: 'كبسولات أوميجا 3 لصحة القلب والدماغ، مستخلص من زيت السمك',
    inStock: true,
    rating: 4.4,
    reviews: 78,
    discount: 13,
    isNew: true
  },
  {
    id: '8',
    name: 'كريم واقي الشمس',
    nameEn: 'Sunscreen Cream',
    price: 42.00,
    image: 'https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Skincare',
    description: 'كريم واقي من الشمس SPF 50، مقاوم للماء ومناسب لجميع أنواع البشرة',
    inStock: true,
    rating: 4.5,
    reviews: 134,
    isBestseller: true
  },
  {
    id: '9',
    name: 'حليب الأطفال',
    nameEn: 'Baby Formula',
    price: 38.00,
    image: 'https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Baby Products',
    description: 'حليب صناعي للأطفال، مدعم بالفيتامينات والمعادن الأساسية',
    inStock: true,
    rating: 4.6,
    reviews: 201
  },
  {
    id: '10',
    name: 'ميزان حرارة رقمي',
    nameEn: 'Digital Thermometer',
    price: 25.00,
    image: 'https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Medical Devices',
    description: 'ميزان حرارة رقمي سريع ودقيق، مناسب للأطفال والكبار',
    inStock: true,
    rating: 4.3,
    reviews: 87
  },
  {
    id: '11',
    name: 'معجون أسنان',
    nameEn: 'Toothpaste',
    price: 15.75,
    image: 'https://images.pexels.com/photos/3685530/pexels-photo-3685530.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Personal Care',
    description: 'معجون أسنان بالفلورايد، يحمي من التسوس ويبيض الأسنان',
    inStock: true,
    rating: 4.1,
    reviews: 156
  },
  {
    id: '12',
    name: 'فيتامين سي',
    nameEn: 'Vitamin C',
    price: 32.00,
    originalPrice: 40.00,
    image: 'https://images.pexels.com/photos/3683107/pexels-photo-3683107.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vitamins & Supplements',
    description: 'أقراص فيتامين سي لتقوية المناعة، 1000 ملغ',
    inStock: true,
    rating: 4.7,
    reviews: 112,
    discount: 20,
    isBestseller: true
  }
];